nginx_version: 1.27.1
output_package: deb
modules:
  - module: 
      name: ngx_security_headers
      git_url: https://github.com/GetPageSpeed/ngx_security_headers.git
  - module:
      name: ngx_http_proxy_connect_module
      patch: ./ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_102101.patch
      git_url: https://github.com/chobits/ngx_http_proxy_connect_module.git
configure_params:
  - "--with-openssl-opt='enable-tls1_3'"
  - "--with-http_ssl_module"
  - "--with-file-aio"
  - "--with-http_mp4_module"
  - "--with-http_gzip_static_module"
  - "--without-http_ssi_module"
  - "--without-http_autoindex_module"
  - "--without-http_split_clients_module"
  - "--without-stream_split_clients_module"
  - "--without-http_fastcgi_module"
  - "--without-http_uwsgi_module"
  - "--without-http_scgi_module"