name: build deb

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-deb:
    name: build deb
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install soft 
        run: sudo apt-get install -y locales wget build-essential autogen automake autoconf autotools-dev libgd-dev libreadline-dev libncurses5-dev libpcre3 libpcre3-dev libpng-dev dh-make quilt lsb-release debhelper dpkg-dev dh-systemd pkg-config zlib1g-dev libssl-dev openssl git perl libtool tar unzip xutils-dev python3-apt
      - name: Install python dependencies
        run: pip3 install -r requirements.txt
      - name: Build
        run: sudo mkdir -p /usr/src/nginx/modules && sudo chmod -R 777 /usr/src/nginx && ./main.py build -f config.yaml -r $GITHUB_RUN_NUMBER
      - name: Archive *.deb package
        uses: actions/upload-artifact@v2
        with:
          name: nginx
          if-no-files-found: error
          path: |
            *.deb
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'nginx*'
