name: build deb

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-deb:
    name: build deb
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install soft 
        run: sudo apt-get install -y locales wget build-essential autogen automake autoconf autotools-dev libgd-dev libreadline-dev libncurses5-dev libpcre3 libpcre3-dev libpng-dev dh-make quilt lsb-release debhelper dpkg-dev dh-systemd pkg-config zlib1g-dev libssl-dev openssl git perl libtool tar unzip xutils-dev python3-apt
      - name: Install python dependencies
        run: pip3 install -r requirements.txt
      - name: Build
        run: rm -rf /usr/src/nginx && ./main.py build -f config.yaml -r $GITHUB_RUN_NUMBER
