name: build deb

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-deb:
    name: build deb
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Build
        run: sudo mkdir -p /usr/src/nginx/modules && sudo ./main.py build -f config.yaml -r $GITHUB_RUN_NUMBER
